services:
  news-web-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3045:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - api
