services:
  news-web-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3045:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://api:8000/api/v1
    depends_on:
      - api
